"""test for users

Revision ID: 415401c57598
Revises: 
Create Date: 2024-11-27 14:07:51.874792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415401c57598'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
