"""delete test for users

Revision ID: 986d4d6d9ef2
Revises: 415401c57598
Create Date: 2024-11-27 14:09:31.543842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986d4d6d9ef2'
down_revision = '415401c57598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
